version: 0.0
os: linux

# 해당 경로로 S3에서 Zip파일을 받아옵니다. 현재는 source: /로 전체 파일을 받아옵니다
files:
  - source: /
    destination: /home/ec2-user/applications
file_exists_behavior: OVERWRITE
# 현재 경로의 deploy.sh 파일 실행
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root